[build]
  functions = "dist/portfolio/browser"
  publish = "dist/portfolio/browser"
  base = "dist/portfolio/browser"

[redirects]
  /experience/*  /experience
  /about/*  /about
  /projects/*  /projects
  /contact/*  /contact


